theme = "base16_default"

[editor]
auto-save = true
true-color = true
popup-border = "all"

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
